language: php

php:
  - 5.5
  - 5.6
# - 7.0

sudo: false

install:
  - git clone https://github.com/krakjoe/pthreads.git;
    pushd pthreads;
    if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then
        git checkout master;
    else
        git checkout seven;
    fi;
    phpize;
    ./configure;
    make;
    make install;
    popd;
    echo "extension=pthreads.so" >> "$(php -r 'echo php_ini_loaded_file();')"
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then
        vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml;
    else
        phpdbg -qrr vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml;
    fi

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt

notifications:
  slack: icicleio:zLkB18HsYCz8TbdK7RVqbi48
