language: php

php:
  - 7.0
  - 7.1
  - nightly

sudo: false

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction --prefer-source
  - travis/install-pthreads.sh

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - composer require satooshi/php-coveralls dev-master
  - vendor/bin/coveralls -v --exclude-no-stmt
